---
- name: Włącz zaporę i otwórz porty 22 i 80 (UFW - Ubuntu)
  ufw:
    rule: allow
    port: "{{ item }}"
  loop:
    - 22
    - 80
  when: ansible_distribution == "Ubuntu"

- name: Włącz zaporę UFW (Ubuntu)
  ufw:
    state: enabled
  when: ansible_distribution == "Ubuntu"

- name: Włącz firewalld (CentOS/openSUSE)
  service:
    name: firewalld
    state: started
    enabled: yes
  when: ansible_distribution in ["CentOS", "openSUSE Leap"]

- name: Otwórz porty 22 i 80 (firewalld - CentOS/openSUSE)
  firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    state: enabled
    immediate: yes
  loop:
    - 22
    - 80
  when: ansible_distribution in ["CentOS", "openSUSE Leap"]

